CREATE DATABASE IF NOT exists AGGREGATOR;

CREATE TABLE AGGREGATOR.INVOICE (
	ID VARCHAR(100) NOT NULL,
	INVOICE_ID varchar(100) NULL,
	VALUE DOUBLE PRECISION NULL,
	CREATED_AT INTEGER NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE AGGREGATOR.CREDIT_NOTE (
	ID VARCHAR(100) NOT NULL,
	CREDIT_NUMBER varchar(100) NULL,
	VALUE DOUBLE PRECISION NULL,
	CREATED_AT INTEGER NULL,
	PRIMARY KEY (ID)
);



